[package]
name = "arch"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
amd-sev = []

[dependencies]
libc = ">=0.2.39"
vm-memory = { version = "0.7.0", features = ["backend-mmap"] }

arch_gen = { path = "../arch_gen" }
utils = { path = "../utils" }

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = { version = ">=0.2", features = ["fam-wrappers"] }
kvm-ioctls = { git = 'https://github.com/slp/kvm-ioctls', branch = 'amdsev' }

[dev-dependencies]
utils = { path = "../utils" }
device_tree = ">=1.1.0"
