[package]
name = "cpuid"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"

[dependencies]
vmm-sys-util = ">=0.7.0"

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = { version = ">=0.2", features = ["fam-wrappers"] }
kvm-ioctls = { git = 'https://github.com/slp/kvm-ioctls', branch = 'amdsev' }
