[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"

[dependencies]
bitflags = "1.2.0"
libc = ">=0.2.85"
vmm-sys-util = ">=0.7.0"

[target.'cfg(target_os = "macos")'.dependencies]
kqueue = "1.0.3"
